/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Conveyor_Long.glb -t -T -I --shadows 
Files: ./public/models/Conveyor_Long.glb [157.38KB] > C:\Users\SSAFY\Documents\GitLab\S10P31S109\frontend\Conveyor_Long-transformed.glb [34.18KB] (78%)
*/

import * as THREE from 'three';
import React, { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    PaletArrow010: THREE.Mesh;
    PaletSide010: THREE.Mesh;
  };
  materials: {
    M_Machn_Conveyor: THREE.MeshStandardMaterial;
    M_ColorPalette: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF(
    '/models/Conveyor_Long-transformed.glb'
  ) as GLTFResult;
  const instances = useMemo(
    () => ({
      PaletArrow: nodes.PaletArrow010,
      PaletSide: nodes.PaletSide010,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props} castShadow receiveShadow>
      {(instances: ContextType) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.PaletArrow
        position={[0, 0.967, 0]}
        rotation={[Math.PI, -1.57, Math.PI]}
      />
      <instances.PaletSide
        position={[0, 0.967, 0]}
        rotation={[Math.PI, -1.57, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/models/Conveyor_Long-transformed.glb');
