/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/098-belt.glb -t -T -I 
Files: ./public/models/098-belt.glb [59.59KB] > C:\Users\SSAFY\Documents\GitLab\S10P31S109\frontend\098-belt-transformed.glb [6.95KB] (88%)
*/

import * as THREE from 'three';
import React, { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh;
    Plane002: THREE.Mesh;
    Vert: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/098-belt-transformed.glb') as GLTFResult;
  const instances = useMemo(
    () => ({
      Plane: nodes.Plane001,
      Plane1: nodes.Plane002,
      Vert: nodes.Vert,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props} castShadow receiveShadow>
      {(instances: ContextType) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.Plane scale={[0.999, 1, 1]} />
      <instances.Plane1 />
      <instances.Vert />
    </group>
  );
}

useGLTF.preload('/models/098-belt-transformed.glb');
