/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/BigShelvesWoodBox.glb -t -T -I --shadows 
Files: ./public/models/BigShelvesWoodBox.glb [320.57KB] > C:\Users\SSAFY\Documents\GitLab\S10P31S109\frontend\BigShelvesWoodBox-transformed.glb [156.82KB] (51%)
*/

import * as THREE from 'three';
import React, { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    BigShelvesWoodBox_1: THREE.Mesh;
  };
  materials: {
    BigShelvesWoodBox: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF(
    '/models/BigShelvesWoodBox-transformed.glb'
  ) as GLTFResult;
  const instances = useMemo(
    () => ({
      BigShelvesWoodBox: nodes.BigShelvesWoodBox_1,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props} castShadow receiveShadow>
      {(instances: ContextType) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.BigShelvesWoodBox />
    </group>
  );
}

useGLTF.preload('/models/BigShelvesWoodBox-transformed.glb');
