/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/geomarker.glb -t -T 
Files: ./public/models/geomarker.glb [17.88KB] > C:\Users\m_a_y\OneDrive\문서\SSAFY\S10P31S109\frontend\geomarker-transformed.glb [2.5KB] (86%)
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh;
  };
  materials: {
    SVGMat: THREE.MeshStandardMaterial;
  };
};

export function GeoMarker(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/geomarker-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        rotation={[Math.PI / 2, 0, 0]}
        scale={6.79}
      />
    </group>
  );
}

useGLTF.preload('/models/geomarker-transformed.glb');
