/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/BigShelves04Group3.glb -t -T -I --shadows 
Files: ./public/models/BigShelves04Group3.glb [2.05MB] > C:\Users\SSAFY\Documents\GitLab\S10P31S109\frontend\BigShelves04Group3-transformed.glb [356.14KB] (83%)
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BigShelves04_1: THREE.Mesh
    BigShelves04_2: THREE.Mesh
    BigShelves04_3: THREE.Mesh
    BigShelves04_4: THREE.Mesh
    BigShelvesWoodBox: THREE.Mesh
    Cardboard_box01: THREE.Mesh
    Cardboard_box05: THREE.Mesh
  }
  materials: {
    BigShelvesMetall03: THREE.MeshStandardMaterial
    BigShelvesMetall01: THREE.MeshStandardMaterial
    BigShelvesWood: THREE.MeshStandardMaterial
    BigShelvesMetall02: THREE.MeshStandardMaterial
    BigShelvesWoodBox: THREE.MeshStandardMaterial
    Cardboard_box06: THREE.MeshStandardMaterial
    Cardboard_box05: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = createContext({} as ContextType)
export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/BigShelves04Group3-transformed.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      BigShelves: nodes.BigShelves04_1,
      BigShelves1: nodes.BigShelves04_2,
      BigShelves2: nodes.BigShelves04_3,
      BigShelves3: nodes.BigShelves04_4,
      BigShelvesWoodBox: nodes.BigShelvesWoodBox,
      Cardboardbox: nodes.Cardboard_box01,
      Cardboardbox1: nodes.Cardboard_box05,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BigShelvesWoodBox />
      <instances.Cardboardbox />
      <instances.Cardboardbox1 />
      <instances.BigShelves />
      <instances.BigShelves1 />
      <instances.BigShelves2 />
      <instances.BigShelves3 />
    </group>
  )
}

useGLTF.preload('/BigShelves04Group3-transformed.glb')
