spring:
  application:
    name: smartfactory
  profiles:
    include:
      - db
      - kafka
      - redis
      - actuator
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      label: main, master
