/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/WareBig_Walls_Wind.glb -T -t -I 
Files: ./public/models/WareBig_Walls_Wind.glb [1.42MB] > /Users/yizhi/vscode/SSAFY/S10P31S109/frontend/WareBig_Walls_Wind-transformed.glb [693.4KB] (51%)
*/

import * as THREE from 'three';
import React, { useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object001: THREE.Mesh;
    WareBig_Column: THREE.Mesh;
    WareBig_W: THREE.Mesh;
    WareBig_Walls_Wind_2: THREE.Mesh;
    WareBig_Walls_Wind_3: THREE.Mesh;
    WareBig_Walls_Wind_4: THREE.Mesh;
    WareBig_Wind: THREE.Mesh;
    WareBig_Windglass: THREE.Mesh;
  };
  materials: {
    WarehouseMetal01: THREE.MeshStandardMaterial;
    WarehouseConcrete1a: THREE.MeshStandardMaterial;
    WarehouseMetal02: THREE.MeshStandardMaterial;
    WarehouseConcrete3: THREE.MeshStandardMaterial;
    WarehouseConcrete4: THREE.MeshStandardMaterial;
    WarehouseConcrete1: THREE.MeshStandardMaterial;
    WarehouseWindow: THREE.MeshStandardMaterial;
    WarehouseWindglasses: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

const context = createContext({} as ContextType);
export function Instances({
  children,
  ...props
}: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF(
    '/models/WareBig_Walls_Wind-transformed.glb'
  ) as GLTFResult;
  const instances = useMemo(
    () => ({
      Object: nodes.Object001,
      WareBigColumn: nodes.WareBig_Column,
      WareBigW: nodes.WareBig_W,
      WareBigWallsWind: nodes.WareBig_Walls_Wind_2,
      WareBigWallsWind1: nodes.WareBig_Walls_Wind_3,
      WareBigWallsWind2: nodes.WareBig_Walls_Wind_4,
      WareBigWind: nodes.WareBig_Wind,
      WareBigWindglass: nodes.WareBig_Windglass,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props} castShadow receiveShadow>
      {(instances: ContextType) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.Object />
      <instances.WareBigColumn />
      <instances.WareBigW />
      <instances.WareBigWind />
      {/* <instances.WareBigWindglass /> */}
      <instances.WareBigWallsWind />
      <instances.WareBigWallsWind1 />
      <instances.WareBigWallsWind2 />
    </group>
  );
}

useGLTF.preload('/models/WareBig_Walls_Wind-transformed.glb');
