/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/WareBig_Floor.glb -T -t 
Files: ./public/models/WareBig_Floor.glb [228.48KB] > /Users/yizhi/vscode/SSAFY/S10P31S109/frontend/WareBig_Floor-transformed.glb [92.04KB] (60%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    WareBig_Floor_1: THREE.Mesh;
  };
  materials: {
    WarehouseConcrete2: THREE.MeshStandardMaterial;
  };
};

export function WareBigFloor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/WareBig_Floor-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <mesh
        geometry={nodes.WareBig_Floor_1.geometry}
        material={materials.WarehouseConcrete2}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/models/WareBig_Floor-transformed.glb');
