/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/WareBig_Roof.glb -T -t 
Files: ./public/models/WareBig_Roof.glb [1.99MB] > /Users/yizhi/vscode/SSAFY/S10P31S109/frontend/WareBig_Roof-transformed.glb [380.37KB] (81%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    WareBig_Detail: THREE.Mesh;
    WareBig_Lamps: THREE.Mesh;
    WareBig_Metal: THREE.Mesh;
    WareBig_Roof_1: THREE.Mesh;
  };
  materials: {
    WarehouseMetal04: THREE.MeshStandardMaterial;
    WareLight: THREE.MeshStandardMaterial;
    WarehouseMetal01: THREE.MeshStandardMaterial;
    WarehouseRoof: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function WareBigRoof(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/WareBig_Roof-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, 8.7, 0]}>
      <mesh
        geometry={nodes.WareBig_Detail.geometry}
        material={materials.WarehouseMetal04}
      />
      <mesh
        geometry={nodes.WareBig_Lamps.geometry}
        material={materials.WareLight}
      />
      <mesh
        geometry={nodes.WareBig_Metal.geometry}
        material={materials.WarehouseMetal01}
      />
      <mesh
        geometry={nodes.WareBig_Roof_1.geometry}
        material={materials.WarehouseRoof}
      />
    </group>
  );
}

useGLTF.preload('/models/WareBig_Roof-transformed.glb');
