spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          password: ${GIT_PASSWORD}
          search-paths:
            - '{application}'
          username: smart-factory
          clone-on-start: true
          default-label: master
server:
  port: 8888
